@startuml

title
NooSphere One-Time Request
end title


actor "End User" as User
participant "NooSphere Hub" as Hub
participant "NooSphere Authenticator (Keycloak, Wallet)" as Auth
participant "Smart Contract" as Contract
participant "NooSphere Validator" as Validator
participant "NooSphere Queue" as Queue
participant "NooSphere Node" as Node
participant "AI Processor" as AI


User -> Hub ++: 1. Hub Login.
User++
Hub --> Auth ++: 1.1. Auth Login
Auth--> Hub : 1.2. Auth Login Results
deactivate Auth
Hub --> Hub: 1.3. Create Session
Hub --> User: 1.4. Return session
deactivate User
deactivate Hub


User --> Hub++: 2. Search Features
User++
Hub --> Contract++: 2.1. Search Features
Contract --> Hub: 2.2. Search Features Results
deactivate Contract
Hub --> User: 2.3. Return Search Features Results
deactivate User
deactivate Hub


User --> User++: 3. Select Feature
User --> Hub++: 3. Submit One-Time Request
Hub --> Auth++: 3.1. Sign Transaction Request
Auth --> Hub: 3.2. Sign Transaction Results
deactivate Auth
Hub --> Contract++: 3.3. Submit One-Time Request
Contract --> Contract: 3.4. Update State and Make Transaction
Contract --> Contract: 3.5. Emit Event
Contract --> Hub: 3.6 Listen Events
deactivate Contract
Hub --> Queue++: 3.7 Generate One-Time Execution
Queue --> Node++: 3.8 Listen Queues
deactivate Queue
Node --> AI++: 3.9 Request One-Time Execution
AI --> AI: 3.10 Execute One-Time Request
AI --> AI: 3.11 Generate Execution Results
AI --> Queue: 3.12 Send Execution Results
deactivate AI
Queue --> Node: 3.13 Listen Queues
Node --> Node: 3.14 Create Proof
Node --> Queue++: 3.15 Send Results with Proof
deactivate Node

Queue --> Validator++: 3.16 Listen Queue
Validator --> Validator: 3.17 Verify Proof
Validator --> Queue: 3.18 Send Validation Results
deactivate Validator
deactivate Queue

Queue --> Hub: 3.19 Listen Queues
Hub --> Contract++: 3.20 Submit One-Time Execution Results
Contract --> Contract: 3.21. Update State and Make Transaction
Contract --> Contract: 3.5. Emit Event
Contract --> Hub: 3.22 Listen Events
deactivate Contract
Hub --> User: 3.23 Return One-Time Execution Results

deactivate Contract
deactivate User
deactivate Hub



@enduml