@startuml
left to right direction
skinparam backgroundColor #F5F5F5
skinparam shadowing false
skinparam componentStyle rectangle
skinparam ArrowColor #1E90FF
skinparam ArrowThickness 2
skinparam roundcorner 20
skinparam rectangle {
    FontName Calibri
    FontSize 12
    BackgroundColor #EFF3FE
    FontColor #000000
    BorderColor #4682B4
}

skinparam actor {
    FontName Calibri
    FontSize 12
    BackgroundColor #FFFFFF
    FontColor #000000
    BorderColor #000000
}

skinparam titleFontName Calibri
skinparam titleFontSize 22
skinparam titleFontColor #000000

title
NooSphere Architecture
end title

actor "End User\n(dApp)" as User
actor "AI Model Creator" as AIMC

package "NooSphere Ecosystem" #DFF0D8 {
    left to right direction
    package "NooSphere Hub" as Hub #BFF3FE{
        left to right direction
        rectangle "Request API" as ReqAPI
        rectangle "Response API" as RespAPI
    }

    package "Smart Contract Layer" as Contract #FFF5E1 {
        left to right direction
        rectangle "Escrow" as Escrow
        rectangle "Request Manager" as ReqManager
    }

    rectangle "NooSphere Node Layer" as Node #CFE2F3 {
        top to bottom direction
        rectangle "Node 1\n- Event Listener\n- Proof Generator" as Node1
'        rectangle "Node 2\n- Event Listener\n- Proof Generator" as Node2
        ...
        rectangle "Node N\n- Event Listener\n- Proof Generator" as NodeN
    }
}

package "Compute Layer" as Compute #E3F2FD {
    top to bottom direction
    rectangle "Processor 1\n- Compute Engine" as AI1
'    rectangle "Processor 2\n- Compute Engine" as AI2
    ...
    rectangle "Processor N\n- Compute Engine" as AIN
}

User --> ReqAPI : Submit Request
ReqAPI --> Escrow : Forward Request
Escrow --> ReqManager : Forward Request

ReqManager --> Node : Emit Event
Node --> Compute : Trigger Computation
Compute --> RespAPI : Return Results + Proof

RespAPI --> User : Return Results to User
AIMC --> Compute : Deploy AI Models

@enduml