@startuml
top to bottom direction

actor "End User (dApp)" as User

rectangle "NooSphere" {
  actor "NooSphere Hub" as Hub
  actor "Smart Contract" as Contract
  actor "NooSphere Node" as Node
  actor "AI Model Processor" as CNode

  usecase "Request One-Time Computation" as UC1
  usecase "Request Recurring Computation" as UC2
  usecase "Cancel Computation" as UC3
  usecase "Receive Computation Result" as UC4
  usecase "Send Computation Request" as UC5
  usecase "Generate Event" as UC7
  usecase "Listen Event" as UC8
  usecase "Generate Computation Result" as UC9
  usecase "Generate Proof" as UC10
  usecase "Verify Proof" as UC11
}

User --> UC1
User --> UC2
User --> UC3

Hub --|> UC1
Hub --|> UC2
Hub --|> UC3
Hub --|> UC4
Node --|> UC5
UC7 --> UC8
Contract --|> UC7
Node --|> UC8
UC8 --> Node


'Contract --|> UC1
'Contract --|> UC2
'Contract --|> UC3
'Contract --|> UC4

UC1 ..> UC4 : <<include>>
UC2 ..> UC4 : <<include>>
Hub ..> Contract : <<include>>

CNode --|> UC9
'CNode ..> UC9 : <<delivers>>
'UC6 ..> UC9 : <<delivers>>
UC9 --> Node

UC5 --> CNode

Node --> UC10
UC10 --> UC4 : Send Result and Proof

UC4 --> UC11

UC11 --> User

@enduml