@startuml

title
NooSphere One-Time Request SDK (Delegate)
end title


actor "End User" as User
participant "Wallet" as Auth
participant "Smart Contract" as Contract
participant "NooSphere Verifier" as Verifier
participant "NooSphere Node" as Node
participant "AI Processor" as AI


group "1 Request Search Features" Steps
  User --> Contract: 1.1. Search¸Features
  Contract --> User: 1.2. Return Features
  User --> User: 1.3. Select Feature
end

group "2 Submit One-Time Request" Steps
  User --> Auth: 2.1. Create Signature
  Auth --> User: 2.2. Return Signature
  User --> Contract: 2.3. Submit One-Time Request with Signature
  Contract --> Contract: 2.4. Register Request with data
  Contract --> Contract: 2.5. Create Transaction
  Contract --> Contract: 2.6. Emit Event
end

group "3 Process One-Time Request" Steps
  Contract --> Node: 3.1 Listen Events
  Node --> Node: 3.2 Parse Event
  Node --> Node: 3.3 Prepare One-Time Execution
  Node --> AI: 3.4 Request One-Time Execution
  AI --> AI: 3.5 Execute One-Time Request
end

group "4 Process One-Time Response" Steps
  AI --> AI: 4.1 Prepare Execution Results
  AI --> Node: 4.2 Send Execution Results with AI Processor Address
  Node --> Auth: 4.3. Create Signature
  Auth --> Node: 4.4. Return Signature
  Node --> Node: 4.5 Create Proof
  Node --> Contract: 4.6 Register Results and Proof with Node, AI Processor Addresses
  Contract --> Contract: 4.7. Create Transaction
  Contract --> Contract: 4.8 Emit Event
end

group "5 Verify One-Time Response" Steps
  Contract --> Verifier: 5.1 Listen Events
  Verifier --> Verifier: 5.2 Parse Event
  Verifier --> Auth: 5.3. Create Signature
  Auth --> Verifier: 5.4. Return Signature
  Verifier --> Verifier: 5.5 Verify Proof
  Verifier --> Contract: 5.6 Register Verification Results
end

group "6 Process One-Time Request Accounting" Steps
  Contract --> Contract: 6.1 Process Verification Results
  Contract --> Contract: 6.2 Parse One-Time Response
  Contract --> Contract: 6.3 Parse Node, AI Model Creator, AI Processor Addresses
  Contract --> Contract: 6.4. Calculate Fees and Rewards
  Contract --> Contract: 6.5. Update State
  Contract --> Contract: 6.6. Create Transaction
  Contract --> Contract: 6.7 Emit Event
end

group "7 Process One-Time Response" Steps
  Contract --> User: 7.1 Listen Events
  User --> User: 7.2 Parse Event
  User --> User: 7.3 Retrieve One-Time Response
end


@enduml